# Generated by Django 3.1.4 on 2021-07-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210720_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default=True, max_length=3000),
        ),
    ]
